### ISSUE TITLE
ConsenLogging Events are not send to Tag Management Dispatcher

### ISSUE THREAD

**Issue by JoeCrumbs** [Tealium/tealium-kotlin#111]
Hi,
we want to use the Tealium Consent Logging Feature to save our Consents in the Eventstore. Additionally we want to add some custom data in a Tealium IQ Extension, before sending these Events. However when consentManagerLoggingEnabled = true is set, the consent logging events (for example "grant_partial_consent") are send directly to eventstream - there is no partial_consent_event send to the Tag Management Dispatcher. is this behaviour intended? I think the other Tealium SDKs behave differently.

The Event "update_consent_cookie" is send to the Tag Management Dispatcher, but persisted data-layer values (example: tealium.dataLayer.putString("my_string", "my_string_value")) are not included.

**Comment by jameskeith** [comment]
Hi @JoeCrumbs 

Thanks for raising the query - I believe all of what you've described were as originally designed, but I can certainly see the uses of sending the events via the TagManagement dispatcher. So I'll get this raised internally and hopefully get support for this out in the near future.

thanks
James

**Comment by jameskeith** [comment]
@JoeCrumbs - we've updated this behaviour in [v1.2.6](https://github.com/Tealium/tealium-kotlin/releases/tag/1.2.6) so consent logging events will be sent as a regular Dispatch to all Dispatchers, which means you'll receive it in the TagManagement dispatcher along with any context data from the datalayer etc.
Please let us know if you need anything else
