### ISSUE TITLE
Value of app_version in Java vs Kotlin version

### ISSUE THREAD

**Issue by JanIceTea** [Tealium/tealium-kotlin#113]
We've recently updated from the Java to the Kotlin version of Tealium and now we see that the value of app_version seems to be the build version, while in Java it used to be the human readable app version, whereas app_build has the actual app version. Could this be corrected?

**Comment by jameskeith** [comment]
@JanIceTea 
Thanks for flagging this with us - I can see the same behaviour, and of course we'll get this raised and fixed asap.

**Comment by jameskeith** [comment]
@JanIceTea - this should now be fixed as of [v1.2.6](https://github.com/Tealium/tealium-kotlin/releases/tag/1.2.6)
Let us know if you are still having issues
