### ISSUE TITLE
App name is not included if Manifest doesn't use string resource

### ISSUE THREAD

**Issue by vincent-paing** [Tealium/tealium-kotlin#126]
I noticed that app name returns empty if we don't use string resource for `android:label` in Manifest. A potential use case for this is when we're using `manifestPlaceHolder` in `build.gradle`.

```groovy
android {
    buildTypes {
        release {
            manifestPlaceholders = [appName: "My Standard App Name"]
        }
        debug {
            manifestPlaceholders = [appName: "Debug"]
        }
    }
}
```

Easier way to replicate this is in `AndroidManifest`, use a hard coded label

```xml
<application
        ...
        android:label="Non localized string"
        ...
       
</application>
```

**Comment by tamayok** [comment]
@vincent-paing Thanks for your suggestion and submitting a PR. We'll take a look and review your PR.

**Comment by vincent-paing** [comment]
If anyone's having this issue and want to have dynamic app name, current work around is to declare a `resValue` in module level `build.gradle`

```groovy
productFlavors {
  flavor1 {
   resValue "string", "app_name", "Flavor1"
  }
  flavor2 {
   resValue "string", "app_name", "Flavor2"
  }
 }
```

You can then reference `@string/app_name` in your `AndroidManifest.xml`. If you're looking to combine both `buildType` and `productFlavors` such as `Flavor1-Debug, Flavor1-Staging, Flavor2-Debug,Flavor2-Staging`, you can modify the below example

```groovy
android {
  ...
  // delcare variables to use
  productFlavors.all {
    ext.flavorName = null
  }

  buildTypes.all {
    ext.buildTypeName = null
  }

  productFlavors {
    flavorOne {
      flavorName = "flavorOne"
    }
    flavorTwo {
      flavorName = "flavorOne"
    }
  }

  buildTypes {
    staging {
      buildTypeName = "Staging"
    }
    release {
      buildTypeName = ""
    }
  }

  applicationVariants.all { variant ->
    variant.resValue "string", "app_name", '"' + variant.buildType.buildTypeName + '-' + variant.productFlavors.get(0).flavorName + '"'
  }
  ...
}
```
