### ISSUE TITLE
Cannot drop jetifier due to robolectric 4.3.1 dependency

### ISSUE THREAD

**Issue by vincent-paing** [Tealium/tealium-kotlin#128]
Run [bye-bye-jetifier](https://github.com/dipien/bye-bye-jetifier) on a project, it said cannot remove jetifier due to tealium depending on `robolectric 4.3.1`. Upgrading `robolectric` to [at least 4.4](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.4) should solve this issue. [Disabling jetifier will allow our project to has less build time](https://adambennett.dev/2020/08/disabling-jetifier/).

**Comment by jameskeith** [comment]
thanks @vincent-paing for flagging this - robolectric is only a test dependency so I would expect this to only be an issue if you were to build from our source rather than from one of our published binaries - is that the case?

Nevertheless I'll raise a task internally to get this dependency updated in a future release.

**Comment by vincent-paing** [comment]
I think this is an issue if you build from published binaries. Correct me if I'm wrong because I'm kinda blurry on this, I think jetifer crawls through all the files packaged inside the binaries to see if there's any `android.support` imports to convert into `androidx`. It should be safe to ignore or override the version since test dependency doesn't affect release builds, however I would prefer not to workaround this by ignoring the build error.

**Comment by jameskeith** [comment]
@vincent-paing - we've updated all our dependencies in the release of version 1.3.0, and the latest versions for the additional modules, mostly at v1.1.0 - so hopefully this should resolve your issues.
As you mentioned tealium-react-native, you may need to await a newer release of that integration that's been updated to use this latest version of the SDK.
