### ISSUE TITLE
TealiumEvent no longer auto-populates `event_name` in tealium-kotlin

### ISSUE THREAD

**Issue by Scott-Woodward** [Tealium/tealium-kotlin#136]
Hello,
We recently updated to the kotlin SDK and have noticed a large inconsistency. In the old SDK (tealium-android) the `event_name` field was auto-populated when the trackEvent method was called. However, in the tealium-kotlin SDK this is no longer sent by default.
I have inspected the source code of both versions and have confirmed that this issue lies with the SDK and not with any custom logic we have included. This was not noted as a change in the documentation (which as a side note is out of date with your github docs).

It would be greatly appreciated if you could clarify whether this is a bug or if it is intended behaviour going forward.
Thanks

**Comment by jameskeith** [comment]
https://docs.tealium.com/platforms/android-kotlin/data-layer/#deprecated
