### ISSUE TITLE
Caused by java.util.ConcurrentModificationException runtime exception 

### ISSUE THREAD

**Issue by pd90** [Tealium/tealium-kotlin#156]
I am getting the following exception in release builds for Android on crashlytics, any idea why this might be happening I am not able to reproduce it though in my dev environment both in release and debug builds, can it be related to progaurd config issue on prod
Caused by java.util.ConcurrentModificationException
java.util.LinkedHashMap$LinkedHashIterator.nextNode (LinkedHashMap.java:757)
java.util.LinkedHashMap$LinkedKeyIterator.next (LinkedHashMap.java:780)
com.tealium.core.messaging.c.onActivityPaused (SourceFile:90)
com.tealium.core.a$a.onActivityPaused (SourceFile:1)
android.app.Application.dispatchActivityPaused (Application.java:485)
android.app.Activity.dispatchActivityPaused (Activity.java:1449)
android.app.Activity.onPause (Activity.java:2387)
androidx.fragment.app.FragmentActivity.onPause (FragmentActivity.java:417)
android.app.Activity.performPause (Activity.java:8392)
android.app.Instrumentation.callActivityOnPause (Instrumentation.java:1510)
android.app.ActivityThread.performPauseActivityIfNeeded (ActivityThread.java:5245)
android.app.ActivityThread.performPauseActivity (ActivityThread.java:5206)
android.app.ActivityThread.handlePauseActivity (ActivityThread.java:5157)
android.app.servertransaction.PauseActivityItem.execute (PauseActivityItem.java:46)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2325)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8633)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

**Comment by jameskeith** [comment]
Hi @pd90 - I've transferred this to the `tealium-kotlin` repo, as the stacktrace provided suggests it related to this SDK, not the previous Java one at `tealium-android`

I believe that this issue is resolved in version [1.2.8](https://github.com/Tealium/tealium-kotlin/releases) and above - can I suggest upgrading to the latest version (currently 1.3.0) and retesting please?

**Comment by pd90** [comment]
@jameskeith I will try and upgrading to latest version and retesting

**Comment by pd90** [comment]
Hi @jameskeith will the versions of the following dependencies remain the same or are their any upgrades to them too, to be precise will the upgrade to 1.3.0 affect the following ones in any way?
implementation 'com.tealium:kotlin-tagmanagement-dispatcher:1.0.5'
implementation 'com.tealium:kotlin-collect-dispatcher:1.0.4'
implementation 'com.tealium:kotlin-visitor-service:1.0.4'

**Comment by jameskeith** [comment]
@pd90 - yes, you should bump those dependencies up to the latest versions as well. which should be `1.1.0` for each of those mentioned.
