### ISSUE TITLE
AwDataDirLock Issue

### ISSUE THREAD

**Issue by mayuce** [Tealium/tealium-kotlin#174]
Hi everyone! This issue has been happening since we have implemented the library to the app. The issue log is:

- Fatal Exception: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process nl.VakantieVeilingen.android (pid 25734), lock owner nl.VakantieVeilingen.android (pid 24385)

-        at org.chromium.android_webview.AwDataDirLock.b(AwDataDirLock.java:106)
-        at org.chromium.android_webview.AwBrowserProcess.j(AwBrowserProcess.java:142)
-        at com.android.webview.chromium.b1.e(b1.java:228)
-        at com.android.webview.chromium.b1.b(b1.java:347)
-        at com.android.webview.chromium.WebViewChromiumFactoryProvider.n(WebViewChromiumFactoryProvider.java:321)
-        at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:301)
-        at android.webkit.WebView.<init>(WebView.java:678)
-        at android.webkit.WebView.<init>(WebView.java:604)
-        at android.webkit.WebView.<init>(WebView.java:587)
-        at android.webkit.WebView.<init>(WebView.java:574)
-        at android.webkit.WebView.<init>(WebView.java:564)
-        **at com.tealium.tagmanagementdispatcher.d$b.invokeSuspend(SourceFile:4)**
-        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
-        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
-        at android.os.Handler.handleCallback(Handler.java:873)
-        at android.os.Handler.dispatchMessage(Handler.java:99)
-        at android.os.Looper.loop(Looper.java:214)
-        at android.app.ActivityThread.main(ActivityThread.java:7050)
-        at java.lang.reflect.Method.invoke(Method.java)
-        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
-        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

We have investigated this but there is no other task is running that can use the WebView, it's also happening in the first seconds of the session:
![Screenshot 2022-07-08 at 13 49 10](https://user-images.githubusercontent.com/23086774/177986536-e8c870f7-865a-4a4f-9bd9-23eccf5551eb.png)

Mostly (%96) on Samsung devices (Galaxy A21s is %82 of them):
![Screenshot 2022-07-08 at 13 49 48](https://user-images.githubusercontent.com/23086774/177986631-da9ff432-97dd-4fc6-824c-109fb159b231.png)

Can you help us about this? Thanks in advance!

Current used Tealium SDK version: 1.4.0

**Comment by jameskeith** [comment]
Hi @mayuce 

Thanks for raising this with us - The Tag Management features of the SDK do make use a WebView so if you are using the SDK/TagManagement features in multiple processes within your app, then you will need to make allowances for that as outlined in the documentation here
https://docs.tealium.com/platforms/android-kotlin/install/#multiprocess-apps

I'd agree that it's rather strange to see this affect specific devices more than others though - as this issue will only be apparent in apps that explicitly run multiple processes, and it should therefore affect every device that spawns both processes.

**Comment by mayuce** [comment]
Hi @jameskeith ! 

Sorry for my late response firstly; that's the thing, we **don't** have **multi-process** within the app but it still **crashes**. Due to that we already have added the setting cache suffix code as below before the application created (due to injection App invokes this line before Tealium instance has been created),
App.kt code snippet:

```
override fun onCreate() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            if (packageName != getProcessName()) {
                WebView.setDataDirectorySuffix(getProcessName())
            }
        }
        super.onCreate()
        .....
}
```
Thanks for your help!

**Comment by jameskeith** [comment]
Hi @mayuce 

Thanks for the additional information. I can see what the code above is trying to do, but you can see from the original crash report that the values from `packageName` and `getProcessName` are going to be the same for this crash - `getProcessName` will return the same value as `packageName` with the addition of the `:<process_name>` appended, but you've already confirmed that you are not running multiple processes.

I fear that we're not going to be able to assist much with this - I've read through the Chromium bug report and the [summary at comment 225](https://bugs.chromium.org/p/chromium/issues/detail?id=558377#c225) describes the overarching issue here - this bug seems to occur when a previous instance of your app has been terminated by Android/OS, but has actually failed to safely terminate, and thus left the directory lock present on the DataDirectory used by the WebView. When the user attempts the re-open your app, the lock is still present and thus the WebView fails to lock the directory.

It's interesting that the vast majority of reporters on that bug report point out that they too are seeing it almost exclusively on Samsung devices, and the frequencies seem to change depending on which security patch the device has from Samsung.
For the record, I've not been able to reproduce this locally so I'm not able to attempt to debug any possible causes.

**Comment by mayuce** [comment]
Hi @jameskeith! Thanks for your advices, seems like you gave some useful information about instances that I can relate this issue. Our application is using Apptentive library to present rate dialog to the user and sometimes I used to see 2 instances of the application in the Recent apps, maybe that's the reason. I'll give it a try and inform you about it, if some another person runs into it, it might be helpful. Thanks again!

**Comment by jameskeith** [comment]
@mayuce - did you get any further with this issue? or did you need anything else from us?

**Comment by mayuce** [comment]
Hi @jameskeith, thanks for checking out; we have used a different kind of a snippet to block this issue. And also another check for does WebView exist on the phone, which significantly decreased the issue to occur. 

So, for those who might face with a similar issue this is what are we doing.

`AppClass`
`override fun onCreate() {
        @SuppressLint("RequiresFeature")
        if (WebViewFeature.isStartupFeatureSupported(
                this,
                WebViewFeature.STARTUP_FEATURE_SET_DATA_DIRECTORY_SUFFIX
            ) && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P
        ) {
            val config = ProcessGlobalConfig()
            val suffix = getProcessName()
            config.setDataDirectorySuffix(this, suffix)
            runCatching {
                ProcessGlobalConfig.apply(config)
            }
        }
        ....
        super.onCreate()
}
`

And before initialising Tealium we do this check:
`
fun isWebViewInitialised(): Boolean =
        WebViewCompat.getCurrentWebViewPackage(context) != null
`

If it is not initialised we don't initialise Tealium and show a screen to user to enable the Webview from their settings.

Thanks,
Have a nice one!
