### ISSUE TITLE
sessionCountingEnabled = false not working as intended ?

### ISSUE THREAD

**Issue by blablubb209** [Tealium/tealium-kotlin#179]
Hello!

I'm trying to reduce the amount of 3rd party requests sent from Tealium by setting
sessionCountingEnabled = false
overrideLibrarySettingsUrl = MyTealiumUTagUrl.

When watching the traffic of my app, I can still see requests send to https://tags.tiqcdn.com/utag/tiqapp.
Shouldn't those be disabled ?

<img width="1728" alt="Screenshot 2022-08-02 at 11 55 01" src="https://user-images.githubusercontent.com/88187335/182347561-8b2cd2e7-22a6-4d81-a149-4b44175ef477.png">

I tested this with different versions:

```
tealiumVersion = '1.3.1'
tealiumLifecycleVersion = '1.1.0'
tealiumTagManagementVersion = '1.1.2'
tealiumInstallReferrerVersion = '1.1.0'
tealiumRemoteCommandDispatcherVersion = '1.1.0'
```

and

```
tealiumVersion = '1.4.2'
tealiumLifecycleVersion = '1.1.1'
tealiumTagManagementVersion = '1.1.2'
tealiumInstallReferrerVersion = '1.1.0'
tealiumRemoteCommandDispatcherVersion = '1.1.1'
```

**Comment by jameskeith** [comment]
@blablubb209 - thanks for raising this with us

The [sessioncountingenabled](https://docs.tealium.com/platforms/android-kotlin/api/tealium-config/#sessioncountingenabled) option, as described on the link is only for customers who are self hosting their Tealium IQ deployment - typically, if you are loading the Tealium IQ features as normal from the tags*.tiqcdn.com CDN, then this option should not be set to `false`

For the majority of our Kotlin SDK releases, the HTTP request for session counting should no longer be made from the `Mobile.html` page used by the TagManagement Dispatcher as shown in your screenshots. However the support for this feature does also require a minimum version of the `Mobile.html` template in Tealium IQ - I'm not able to confirm the version you are using without seeing the Account and Profile that you have configured. 
If you'd prefer to supply this privately then please submit a ticket to support@tealium.com and we can take a further look for you.

**Comment by blablubb209** [comment]
Thanks for the quick response. I'll get the info you need and submit a ticket to [support@tealium.com](mailto:support@tealium.com) as suggested.

Have a nice day
