### ISSUE TITLE
Device in SDK iOS vs Android

### ISSUE THREAD

**Issue by JanIceTea** [Tealium/tealium-kotlin#53]
Hi,
it seems there is a mismatch on the naming and how the device property is implemented in the iOS and Android SDK.
It seems that there is a different between how iOS and Android are reporting the device via the SDK.
In iOS we have:
device_type
model_name
 
where the device_type is the identifier used internally by apple and the model_name is the human readable version.

In Android we only have:
device
which is the internal identifier.

Are there any plans to align these in the near future? It might also already be the case, since we're not using the latest versions.

**Comment by jonathanswong** [comment]
Hi @JanIceTea . Thanks for bringing this to our attention. We can address this in our next release.

**Comment by jameskeith** [comment]
@JanIceTea 
apologies, I'm not sure why you weren't notified about this previously, but we released support for `device_model` and `device_manufacturer` in [v1.1.0](https://github.com/Tealium/tealium-kotlin/releases/tag/1.1.0) some time ago. Hopefully that should help with your use-cases.
Let us know if you need anything further
